In [11]:
from gauss2D import gauss2D
from my_imfilter import my_imfilter
from normalize import normalize
from scipy.misc import imresize
import numpy as np
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import os

''' set up '''
#main_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#img_path = main_path + '/data/cat.bmp'
img_path = r'C:\Users\Irene\Documents\computer vision\homework1-master\data\cat.bmp'
test_image = mpimg.imread(img_path)
'''
plt.imshow(test_image)
test_image = imresize(test_image,0.7,'bilinear')
test_image = test_image.astype(np.single)/255
plt.figure('Image')
plt.imshow(test_image)
plt.show()
'''

TypeError: 'int' object is not iterable

In [16]:
#test_image
dim1 = len(test_image)
dim2 = len(test_image[0])
dim3 = len(test_image[0][0])

In [18]:
print(dim1
,dim2
,dim3)

361 410 3


In [19]:
x=np.zeros((10,20,30))

In [21]:
print(len(x),len(x[0]),len(x[0][0]))

10 20 30


In [22]:
for i in range(5):
    print(i)

0
1
2
3
4


In [24]:
test_image[0][0][2]

121

In [47]:
x1 = np.arange(9).reshape((3, 3))
print(x1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
sum(sum(np.multiply(x1,x1)))

204

In [52]:
x1[1:1+2,1:1+2]

array([[4, 5],
       [7, 8]])

In [53]:
type(test_image[0][0][1])

numpy.uint8

In [54]:
a=np.zeros((2,3)*3, dtype=np.int)

In [55]:
a[:,:,1]=test_image[1:1+2,3:3+3,1]

In [56]:
a

array([[[[[[  0,   0,   0],
           [  0,   0,   0]],

          [[  0,   0,   0],
           [  0,   0,   0]],

          [[  0,   0,   0],
           [  0,   0,   0]]],


         [[[118, 105,  95],
           [124, 107,  96]],

          [[118, 105,  95],
           [124, 107,  96]],

          [[118, 105,  95],
           [124, 107,  96]]]],



        [[[[  0,   0,   0],
           [  0,   0,   0]],

          [[  0,   0,   0],
           [  0,   0,   0]],

          [[  0,   0,   0],
           [  0,   0,   0]]],


         [[[118, 105,  95],
           [124, 107,  96]],

          [[118, 105,  95],
           [124, 107,  96]],

          [[118, 105,  95],
           [124, 107,  96]]]],



        [[[[  0,   0,   0],
           [  0,   0,   0]],

          [[  0,   0,   0],
           [  0,   0,   0]],

          [[  0,   0,   0],
           [  0,   0,   0]]],


         [[[118, 105,  95],
           [124, 107,  96]],

          [[118, 105,  95],
           [124, 107,  96]],

